# Welcome to Serverless!
#
# This file is the main serverless config file for this service.
# For full config options, see docs.serverless.com

service: quiccasa
frameworkVersion: '2'
useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
  profile: serverless
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
  stage: ${opt:stage, "dev"}
  region: eu-west-1
  deploymentBucket: quiccasa-dev-serverlessdeploymentbucket-ajudt9uilmg6
  environment:
    bucket: ${self:resources.Resources.NewResource.Properties.BucketName}
    region: ${self:provider.region}
    service: ${self:service}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
          Resource:
            - "*"
          Condition:
            StringEquals:
              ses:FromAddress:
                - "sistemisolari.quiccasa@gmail.com"
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
          Resource: { "Fn::Join": [ "", [ "arn:aws:s3:::", "quiccasa-bucket-dev" ] ] }
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
            - "s3:DeleteObject"
          Resource: { "Fn::Join": [ "", [ "arn:aws:s3:::", "quiccasa-bucket-dev", "/*" ] ] }
functions:
  crawl:
    handler: index.crawl
    events:
      - http:
          method: get
          path: crawl
#     - schedule: rate(10 minutes)
#     - schedule: cron(0/30 6-22 ? * MON-FRI *) # times are GMT (6 => GMT-1 summertime => 8, 6 => GMT-1 wintertime => 7)
      - schedule: cron(0 6-20/4 ? * MON-FRI *) # times are GMT
      - schedule: cron(0 6-20/8 ? * SAT-SUN *) # times are GMT
    timeout: 30 # seconds, default is 6
  home:
    handler: index.home
    events:
      - http:
          method: get
          path: /home
  subscribe:
    handler: index.subscribe
    events:
      - http:
          method: get
          path: subscribe
  reset:
    handler: index.reset
    events:
      - http:
          method: get
          path: reset
  unsubscribe:
    handler: index.unsubscribe
    events:
      - http:
          method: get
          path: unsubscribe
  actionUnsubscribe:
    handler: index.actionUnsubscribe
    events:
      - http:
          method: get
          path: actionUnsubscribe
          package:
package:
  exclude:
    - private/**
    - node_modules/**
    - tmp/**
#   - website/**
resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: quiccasa-bucket-dev
